name: staging

on:
  push:
    branches: dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      -
        name: Login to OCIR
        uses: docker/login-action@v2
        with:
          registry: lhr.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.staging
          tags: lhr.ocir.io/lrrho0j0b1ox/orqa-client:latest        
      # - 
      #   name: Restart container
      #   uses: oracle-actions/run-oci-cli-command@v1.1.1
      #   with:
      #     command: container-instances container-instance restart --container-instance-id ocid1.computecontainerinstance.oc1.uk-london-1.anwgiljr6wufqiqa2dpi2zzdsbwbgwa4pd5woigjvebctx25znd4lbdficzq --debug
      #     silent: false
